Collect stops systematically from RIS::Stations
derhuerst/db-hafas-stations pull request #3
Opened 2024-12-17 00:22 UTC by traines-source

As always, this turned out to be a bit less straightforward than intended...

Idea: Take stop information from [RIS::Stations](https://developers.deutschebahn.com/db-api-marketplace/apis/product/ris-stations/api/ris-stations), because this API allows to download all stops with only a few hundred queries and contains basically the same information as HAFAS.

This results in an up to daet

2025-01-10 14:29 UTC, traines-source commented
Updates:
• Groß Gerau has reappeared 
• using smaller weights, still very large though because I need to do `Math.pow(weight, 3)` to counterbalance [this](https://github.com/derhuerst/synchronous-autocomplete/blob/4b7d8e141f77a15299c6f80ea22ed358090a1f38/index.js#L90), didn't succeed to obtain a nice ordering otherwise (and even now, Fulda still appears before Frankfurt(Main) when searching for `F`)
• given that DB HAFAS is now gone, I think there is no reason not to merge it here. I'm also using it in [db-vendo-client](https://github.com/public-transport/db-vendo-client) now in order to optionally enrich station information, because the new APIs return a lot less info. But lmk, otherwise I will create a new package.

2025-02-25 14:17 UTC, traines-source commented
@derhuerst Could you give a quick opinion on whether you see this here or rather in a separate, new package `db-ris-stations`?

Because if the latter is the case, I would do this quite soon because I feel that for certain profiles and use cases of [db-vendo-client](https://github.com/public-transport/db-vendo-client) up-to-date and complete station data is becoming increasingly important (because certain DB APIs only return evaNrs or even just names...). I was even thinking about building an "over-the-air" update functionality into it so that people don't have to update the package once a month...

2025-03-14 13:44 UTC, derhuerst commented
Yesterday, I published a new release `db-hafas-stations@1.1.0` with the last HAFAS-based collection from AFAICT June 2024. I also migrated to ES Modules and async generator functions, which are both breaking changes, so a new release with a new data source would be versioned `2.x` anyways.

This and the fact that HAFAS is now turned off but most use cases for `db-hafas-stations` (that I can imagine) probably don't care where the list comes from but rather that it's as complete and up-to-date as possible lead me to agree: We should publish the `RIS::Stations`-based list as `db-hafas-stations@2.0.0`. 👍

2025-03-14 13:49 UTC, derhuerst commented
> To build, you need to set env vars `DB_API_KEY` and `DB_CLIENT_ID`, which can be obtained via the above link for free (10k requests per month).

It sounds like I (or someone) will have to re-subscribe every two months? 🤔

> Testzugang
> Kostenloser Testzugang für max. zwei Monate, Betriebszeit 24/7, Servicezeit Mo-Fr 08:00-17:00 Uhr, Limits: 10 Anfragen pro Sekunde, 10.000 Anfragen pro Monat

2025-03-14 14:10 UTC, derhuerst reviewed
Do you know how what the weight of foreign stations will be, e.g. Amsterdam Centraal?

That aside, some of the state management and the logging in `build/ris.js` could be improved. I'll comment on that later.

2025-03-14 15:20 UTC, traines-source commented
> Yesterday, I published a new release

:tada: Thanks!

> It sounds like I (or someone) will have to re-subscribe every two months? 🤔

Oh no I didn't notice that, or they changed it... Then the utility of all of this is much more debatable... But so far my access still works and it's older than 2 months, so maybe we're lucky. 

> Do you know how what the weight of foreign stations will be, e.g. Amsterdam Centraal?

421.9 vs e.g. 2543302.1 for Berlin Hbf (see https://mirror.traines.eu/hafas-ibnr-zhv-gtfs-osm-matching/full.ndjson). With `db-hafas-stations-autocomplete` it appears first as soon you have typed `Amster`, while before you only had to type `Ams`, but then other stations in Amsterdam were ranked higher. So yes German stations will have a higher rank but IMHO it is not too difficult to obtain foreign stations (e.g. Paris as before with `Pari`), and it is a Germany-centric dataset anyways (arguably more so than before).

2025-03-14 21:00 UTC, networkException commented on build/ris.js
> +    TRAM: { product: 'tram:', weight: 0.2 },
```suggestion
    TRAM: { product: 'tram', weight: 0.2 },
```

This looks a little off

2025-03-14 21:11 UTC, networkException commented on build/ris.js
> +            s.ril100Ids = stadaStop.ril100Identifiers.map(r => r.rilIdentifier); // TODO more precise mapping to evas?
Taking Ril100 codes from STADA is quite limited sadly (probably missing all `NE-{Bf,Hp,...}` for example).

I have a script taking the excel sheet from https://www.dbinfrago.com/web/schienennetz/betrieb/allgemeine-betriebsinformationen/betriebsstellen-12592996, converting it to CSV, filtering for entries likely to have an eva number, putting https://raw.githubusercontent.com/derf/Travel-Status-DE-IRIS/refs/heads/main/share/stations.json into the mix (for at least some of the codes that start with `PQ`, iirc for EFZ stops) and resolving these to eva number + metadata using RIS::Stations (`POST /v1/stop-places/by-keys` with 500 stations per request).

I'd be happy to implement something like this here as well. This would be so much easier if `/v1/stop-places/{eva}` or `/v1/stop-places/by-position` would just return all the data they have, including Ril100 :/

2025-03-14 23:18 UTC, traines-source commented on build/ris.js
> +            s.ril100Ids = stadaStop.ril100Identifiers.map(r => r.rilIdentifier); // TODO more precise mapping to evas?
Not sure, but NE-... is probably all the stations not run by DB directly, right? Not sure if the effort is worth it for these few stations that are usually small stations as well. From my perspective the Ril100 codes were more like a nice addition since they were there anyways. But I guess for only train stations the number of requests to `/stop-places/by-keys` should not be that high.
At least I personally would be much more interested in all the ifoptIds/DHIDs, which the `/stop-places/by-keys` endpoint seems to know even for ÖPNV stops, because this mapping is really difficult to obtain otherwise (compare https://github.com/traines-source/db-hafas-gtfs-stops-mapping). Thinking about it, that would still only be ~1000 requests to `/stop-places/by-keys` :thinking:  There seems to be a secret `/batch/versions` endpoint that returns all of that for all stops, but the last time I checked, it was not accessible with a "normal" API token :(

2025-03-15 12:18 UTC, traines-source commented on build/ris.js
> +            s.ril100Ids = stadaStop.ril100Identifiers.map(r => r.rilIdentifier); // TODO more precise mapping to evas?
Can't stop thinking about this so I'll try this out now, thanks for the idea! I'll then provide you with the results so that you can build your additional logic for Ris100 on top if you want :)

2025-03-15 12:28 UTC, networkException commented on build/ris.js
> +            s.ril100Ids = stadaStop.ril100Identifiers.map(r => r.rilIdentifier); // TODO more precise mapping to evas?
Good luck :)

Can't check right now but I could imagine that stada is also lacking FFGI for example

2025-03-15 12:34 UTC, networkException commented on build/ris.js
> +            s.ril100Ids = stadaStop.ril100Identifiers.map(r => r.rilIdentifier); // TODO more precise mapping to evas?
Oh also RIS::Stations can't resolve `UE` to Erfurt Hbf, only `UE  P` so that data isn't perfect either 🫠

2025-03-15 13:07 UTC, traines-source commented on build/ris.js
> +            s.ril100Ids = stadaStop.ril100Identifiers.map(r => r.rilIdentifier); // TODO more precise mapping to evas?
Ok big disappointment:
* `/stop-places/by-keys` does return neither the IFOPT nor the Ril100, only evaNumber and stada (stationID). And it can only be queried by evaNumber, stada or Ril100 (!), but not by IFOPT.
* `/stop-places/by-key` on the contrary can be queried by IFOPT, but needs a single request per stop, which makes it infeasible...
* `/stop-places/{evaNumber}/keys` seems to be the only endpoint that returns IFOPTs and Ril100, but also needs a single request per stop...
* `https://apis.deutschebahn.com/db/apis/ris-stations/v1/batch/versions` (note the different URL to e.g. `https://apis.deutschebahn.com/db-api-marketplace/apis/ris-stations/v1/stop-places/by-keys`) still gives Unauthorized for normal API keys...

So in conclusion, no luck for IFOPTs, neither by querying by evaNumber nor by IFOPT (based on the ZHV dataset or sth). But it should work for Ril100, but only by querying by Ril100 (or making one request per train station).

And yes, `FFGI` is (was?) missing from Stada (but I guess this will change since it has only been opened last December), but in return Stada knows about `UE` and `UE   P`. But then I return to my previous stance that I'm not sure it's worth the effort (and brittleness) for these few exceptions...

2025-03-15 13:12 UTC, networkException commented on build/ris.js
> +            s.ril100Ids = stadaStop.ril100Identifiers.map(r => r.rilIdentifier); // TODO more precise mapping to evas?
> But then I return to my previous stance that I'm not sure it's worth the effort (and brittleness) for these few exceptions

Thats fair enough. I was looking on this with Ril100 mapping as my primary use case, but all of this seems quite unfeasible

2025-03-15 13:27 UTC, traines-source commented on build/ris.js
> +            s.ril100Ids = stadaStop.ril100Identifiers.map(r => r.rilIdentifier); // TODO more precise mapping to evas?
Doesn't have to stop you from trying it out, whether as part of this repo or a separate one that just takes db-hafas/ris-stations as one of many sources :)

2025-03-15 13:39 UTC, traines-source commented on build/ris.js
> +            s.ril100Ids = stadaStop.ril100Identifiers.map(r => r.rilIdentifier); // TODO more precise mapping to evas?
Actually you could also have a look at https://github.com/derhuerst/db-stations, which is limited to only train stations (i.e. where Ril100 identifiers would make more sense IMO). But AFAICT it also relies on Stada, and is much more outdated, which poses the question if it doesn't make sense to deprecate it in favor of this one, although there are surely still use cases where one only needs train stations and doesn't want to have 100+MB of ÖPNV stations. Still one could just create a subset of the data here, or, on the contrary, keep db-stations as a repository of the actual HAFAS station data, because for only the train stations it should still be possible to fetch that data via the new HAFAS facades (bahn.de/DB Navigator, i.e. db-vendo-client). So many options :melting_face:

2025-03-15 18:33 UTC, traines-source commented
I have postponed the OTA update functionality to later, depending on how the 2 months subscription limit turns out...

Also, I have made some changes that makes it compatible with node 18 again, if you don't want that, I would have to create a fork anyways, since I do not want to bump db-vendo-client to 22 yet. 

> That aside, some of the state management and the logging in build/ris.js could be improved. I'll comment on that later.

Haven't changed much in that respect yet since I'm not sure what you're aiming at :)

>  I could imagine that stada is also lacking FFGI for example

In the meanwhile, it is now contained in StaDa :tada: (Haven't updated my download link since I haven't rerun the RIS scraping yet.)

2025-03-16 10:36 UTC, traines-source commented on build/ris.js
> +            s.ril100Ids = stadaStop.ril100Identifiers.map(r => r.rilIdentifier); // TODO more precise mapping to evas?
PS. https://bahnvorhersage.de/stationviewer

2025-03-16 21:37 UTC, networkException commented on build/ris.js
> +            s.ril100Ids = stadaStop.ril100Identifiers.map(r => r.rilIdentifier); // TODO more precise mapping to evas?
Interesting, that has a few more `PQ...` stations :)

2025-03-17 19:28 UTC, derhuerst commented on build/ris.js
> +            s.ril100Ids = stadaStop.ril100Identifiers.map(r => r.rilIdentifier); // TODO more precise mapping to evas?
> But AFAICT it also relies on Stada, and is much more outdated, which poses the question if it doesn't make sense to deprecate it in favor of this one

I think we could do this, but only as long as `db-hafas-stations`/`db-ris-stations` stays a superset of `db-stations`.

2025-03-17 20:30 UTC, derhuerst requested changes
I found `discoverRisStations()` and `mergeRisStations()` a bit hard to decipher. Can you restructure the code to have a clear division between the actual business logic and the persistence/caching logic?
I propose
- a more higher-level `doRisStationsRequest()` that integrates caching, so that the calling code is more readable.
- clarifying either through self-explaining code or via comments why we use two request modes `groupBy = 'NONE'` & `groupBy = 'SALES'` (stored with files named `single` & `grouped`)?

2025-03-17 20:30 UTC, derhuerst commented on package.json
> +	"license": "SEE LICENSE IN license-data.md",
`license`'s value must be an [SPDX license expression](https://spdx.github.io/spdx-spec/v2.3/SPDX-license-expressions/).

I *think* that, when using `db-hafas-stations`, *both* the source code's license as well as the data's license apply.

```suggestion
	"license": "ISC AND CC-BY-4.0 AND ODbL-1.0",
```

2025-03-17 20:30 UTC, derhuerst commented on package.json
> +		"license.md",
FYI: AFAICT [`license.md` is included automatically](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#files).

2025-03-17 20:30 UTC, derhuerst commented on package.json
> +		"legacy-build": "node build/stations.js | node build/stations-weight.js | node build/index.js",
Let's remove the legacy build script. We can always retrieve from version control again.

2025-03-17 20:30 UTC, derhuerst commented on build/ris.js
> +import {pipeline} from 'node:stream'
Please use `await pipeline()` from `node:stream/promises` and remove `abortWithError`.

2025-03-17 20:30 UTC, derhuerst commented on build/ris.js
> +        const req = https.request(options, (res) => {
Even though [it's still experimental in Node.js v18](https://nodejs.org/docs/latest-v18.x/api/globals.html#fetch), let's use `fetch()`, it has a slightly higher abstraction level.

Also, please make sure to handle the response status code (check `res.ok` when using `fetch()`).

2025-03-17 20:30 UTC, derhuerst commented on build/ris.js
> +    console.error(options.path);
Either remove this logging or make it conditional (by manually checking an env variable, the Node.js tooling is bad for this).

2025-03-17 20:30 UTC, derhuerst commented on build/ris.js
> +const doRequest = (options, data) => {
Let's clarify that it parses JSON.

```suggestion
const requestJson = async (options, data) => {
```

2025-03-17 20:30 UTC, derhuerst commented on build/ris.js
> +    console.error(options.path);
As above.

2025-03-17 20:30 UTC, derhuerst commented on build/ris.js
> +        throw new Error('Emerg: Max depth reached');
As the `bbox` & `depth`, ideally even more context, to the error to allow for debugging.

```suggestion
        const err = new Error('Emerg: Max depth reached');
        err.bbox = bbox;
        err.depth = depth;
        throw err;
```

2025-03-17 20:30 UTC, derhuerst commented on build/ris.js
> +    await sleep(5000 * Math.random());
Why do we sleep here?

2025-03-17 20:30 UTC, derhuerst commented on build/ris.js
> +        await fs.promises.writeFile(fileName, JSON.stringify(single), 'utf8', err => {
`fs.promises.writeFile()` (or `fs/promises`' `writeFile()`, which is equivalent) doesn't take a callback as the last parameter.

2025-03-17 20:30 UTC, derhuerst commented on build/ris.js
> +        throw new Error('exists ' + fileName);
I assume the file-based persistence should allow the build script to be resumed after an interruption (e.g. because the API's limit is reached or the process got killed)? Then why `throw` here instead of reading the data from the file?

2025-03-17 20:30 UTC, derhuerst commented on build/ris.js
> +const LIMIT_RESULTS = 10000;
Can you elaborate in a comment where you got this limit from?

2025-03-17 20:30 UTC, derhuerst commented on build/ris.js
> +const TMP_PATH = 'tmp/';
Assuming that the data in `TMP_PATH` is like a cache (see discussions below), you should either use `/tmp` (assuming a POSIX system) or [`env-paths`](https://github.com/sindresorhus/env-paths/blob/v3.0.0/readme.md#pathscache).

2025-03-17 20:48 UTC, traines-source commented on package.json
> +	"license": "SEE LICENSE IN license-data.md",
While definitely more machine-readable, it lacks the rights owner info for CC-BY and ODbL (I had considered adding DBInfraGO as contributor, but that also felt odd). According to [npm docs](https://docs.npmjs.com/cli/v11/configuring-npm/package-json#license), `SEE LICENSE IN` is also valid :D But yeah your suggestion also works for me :)

2025-03-17 20:51 UTC, traines-source commented on build/ris.js
> +    await sleep(5000 * Math.random());
Because the API only allows 10 requests/second max, and I think it's always good to stretch out the requests over a longer time to fly under the radar/reduce sudden load.

2025-03-17 20:57 UTC, derhuerst commented on package.json
> +	"license": "SEE LICENSE IN license-data.md",
Didn't know about the `SEE LICENSE IN` part. Also, the SPDX expression `LicenseRef-…` would work.

2025-03-17 20:58 UTC, traines-source commented on build/ris.js
> +        throw new Error('exists ' + fileName);
So yes, one would need to read the data from the file just to check whether the limit was reached. But the real reason is that I wanted to force the user to decide explicitly to either delete the `tmp` folder to start from scratch or comment out the fetching part and only run the merging part (I guess one could introduce a flag/env var for that), in order to avoid accidentally rescraping when wanting to fix a bug or sth in the merging logic, but also avoid accidentally using the cache when wanting to update.

2025-03-17 20:59 UTC, derhuerst commented on package.json
> +	"license": "SEE LICENSE IN license-data.md",
> While definitely more machine-readable, it lacks the rights owner info for CC-BY and ODbL

AFAICT that is not the goal behind SPDX License Expressions. I think the idea is only to inform consumers which licenses they'll have to follow, not which authors to credit.

2025-03-17 21:00 UTC, traines-source commented on build/ris.js
> +const TMP_PATH = 'tmp/';
related to the discussion about file-based persistence, I think it is useful to have this folder directly at your hands for debugging, and because you need to manually delete it in order to scrape again.

2025-03-17 21:00 UTC, derhuerst commented on build/ris.js
> +    await sleep(5000 * Math.random());
Then use [lodash's `throttle()`](https://lodash.com/docs/4.17.15#throttle).

2025-03-17 21:09 UTC, derhuerst commented on build/ris.js
> +        throw new Error('exists ' + fileName);
Then we could split the build process into two separate steps? Seems like a more direct/expressive API for this use case.

2025-03-17 21:11 UTC, derhuerst commented on build/ris.js
> +const TMP_PATH = 'tmp/';
For people who build this from the command line, even `/tmp/db-hafas-stations-abc123` would be "at hand", right?

`/tmp` has some benefits:
- It is recognised right away by people used to POSIX systems.
- It will often be cleared automatically, either periodically or at system shutdown.
- It shows up as pursuable in "disk usage" analysers.

We could print the path it writes temporary files to in the beginning.

2025-03-17 21:16 UTC, traines-source commented on build/ris.js
> +    await sleep(5000 * Math.random());
Is lodash throttle the right tool for that? I think it drops calls and does not stretch them out over it, does it?
Since it's just always ~400 requests I think a very simple approach should suffice. With the current setup, it takes about a quarter of an hour.

2025-03-17 21:21 UTC, derhuerst commented on build/ris.js
> +    await sleep(5000 * Math.random());
True, I got confused. I meant [`p-throttle`](https://github.com/sindresorhus/p-throttle).

2025-03-17 21:23 UTC, traines-source commented on build/ris.js
> +const TMP_PATH = 'tmp/';
> It is recognised right away by people used to POSIX systems.

While I haven't used Windows in a couple of years, why drop it without a need? And when using env-paths it's some really cryptic path, e.g. `/var/folders/jf/f2twvvvs5jl_m49tf034ffpw0000gn/T/MyApp-nodejs` on macos.

> It will often be cleared automatically, either periodically or at system shutdown.

That is precisely not what I would want, e.g. yesterday it was very useful to still have the cached files from two months ago. Maybe we should just give it another name than tmp, e.g. data :)

But I guess in the end not many people should ever use this so I'll just change it to `/tmp` and a configurable env variable :+1:

2025-03-17 21:32 UTC, traines-source commented on build/ris.js
> +    await sleep(5000 * Math.random());
TBH not a fan of dependencies for 1-liners (ok, 3-liners :D)

2025-03-18 11:43 UTC, derhuerst commented on build/ris.js
> +const TMP_PATH = 'tmp/';
If we *do* use `/tmp` it shouldn't matter, but otherwise there should also a be a mechanism that checks how old the stored files are. I highly prefer the less complex design using `/tmp` though.

2025-03-18 11:45 UTC, derhuerst commented on build/ris.js
> +    await sleep(5000 * Math.random());
Do you mean [this 3-liner](https://github.com/sindresorhus/p-throttle/blob/5b566f4eecab5b054840896287e46806585747db/index.js#L14-L115)? I've built this by hand before, and (like most things related to concurrency and state-keeping) it was unexpectedly hard to get it right.

2025-03-18 11:46 UTC, derhuerst commented on build/ris.js
> +    await sleep(5000 * Math.random());
Anyways, keeping the `sleep` is fine with me for a less-used little project like this one, where wasting a bit of time doesn't make a big difference.

2025-03-18 11:51 UTC, traines-source commented on build/ris.js
> +    await sleep(5000 * Math.random());
No, the [3-liner to promisify `setTimeout`](https://github.com/derhuerst/db-hafas-stations/blob/58d4d7179152ba86086a9c1dfd0ff733ba886c6e/build/ris-fetch.js#L19). But yeah then let's keep `sleep` :+1:

2025-03-18 13:06 UTC, derhuerst approved these changes
We're close! I have some questions about the business logic, and some minor nitpicks here and there.

2025-03-18 13:06 UTC, derhuerst commented on build/ris-fetch.js
> +            throw new Error(`Failed to fetch from API: ${response.status}`);
[nitpick]

Add more request details to the error object.

```suggestion
            const err = new Error(`Failed to fetch from API: ${response.status}`);
            err.url = url;
            err.fetchOptions = options;
            err.response = response;
            throw err;
```

2025-03-18 13:06 UTC, derhuerst commented on build/ris-fetch.js
> +        throw new Error(error.message);
Throwing the whole error is much better, because it will give more helpful output, e.g. a more correct stack trace and potentially more details. You can just remove the entire `try`/`catch`.

2025-03-18 13:06 UTC, derhuerst commented on build/ris-fetch.js
> +    const fileName = TMP_PATH + depth + '_' + Object.values(bbox).join('_') + (grouped ? '_grouped' : '_single') + '.json';
Make sure to handle `TMP_PATH` values without a trailing space.

```suggestion
    const fileName = pathJoin(TMP_PATH, depth + '_' + Object.values(bbox).join('_') + (grouped ? '_grouped' : '_single') + '.json');
```

2025-03-18 13:06 UTC, derhuerst commented on build/ris-fetch.js
> +        console.error(fileName);
[nitpick]

Adapt the overly aggressive error-level logging.

2025-03-18 13:06 UTC, derhuerst commented on build/ris-fetch.js
> +        throw new Error('File from previous run exists, consider deleting the tmp dir: ' + fileName);
Not sure I understand the business logic, but shouldn't we check this up front?

- If the file at `fileName` *does work* like a transparent cache, we do we throw here?
- If it is not a cache, this would waste precious API requests, only to then abort because a file already exists.

2025-03-18 13:06 UTC, derhuerst commented on build/ris-fetch.js
> +    await fs.promises.mkdir(TMP_PATH, {recursive: true}, err => {
Remove the callback from the promise-based `mkdir()`.

2025-03-18 13:06 UTC, derhuerst commented on package.json
>  		"through2-concurrent": "^2.0.0",
`through2-concurrent` is superfluous now.

```suggestion
```

2025-03-18 13:06 UTC, derhuerst commented on build/ris-merge.js
> +const data = new PassThrough({
[nitpick]

You could directly use the `ndson.stringify()` stream here.

Or, to remove more code, just write individual JSON lines using `process.stdout.write(JSON.stringify(…) + '\n')` in `mergeStations()`...

2025-03-18 13:06 UTC, derhuerst commented on build/ris-fetch.js
> +    return requestJson(url, options);
Add an `await` to make sure the stack trace contains `doRisStationsRequest()`. (I know, this is highly unintuitive!)

```suggestion
    return await requestJson(url, options);
```

2025-03-18 13:06 UTC, derhuerst commented on readme.md
>  ## Related
Maybe you could add a "building" section that explains that you need access to *both* the RIS::Stations and the StaDa APIs via `$DB_CLIENT_ID`/`$DB_API_KEY`.

2025-03-18 13:06 UTC, derhuerst commented on build/ris-fetch.js
> +    await discoverStadaStations();
[nitpick]

I just ran the script without having enrolled in the StaDa API, and it failed at the very end after a loong series of RIS::Stations requests. Now can either re-do all RIS::Stations requests or manually comment out the line above.

I suggest to do this request first.

2025-03-18 13:06 UTC, derhuerst commented on build/ris-merge.js
> +const verifyCompleteness = (stops) => {
Is this a leftover from development? Why don't we verify the stations in-memory?

2025-03-18 13:06 UTC, derhuerst commented on build/ris-merge.js
> +            .on('data', d => {
You can use async iteration here.

```
        const stations = fs.createReadStream('hafas-stations.ndjson')
             .pipe(ndjson.parse())
        for await (const d of stations) {
            // …
        }
```

2025-03-18 13:06 UTC, derhuerst commented on build/ris-merge.js
> +            // use groupMembers from grouped results
I don't understand the assumptions made here. What happens if `groupMembers` is (already) non-empty?

2025-03-18 13:17 UTC, traines-source commented on build/ris-fetch.js
> +        console.error(fileName);
That it's `error` is for historic reasons when this was still part of the stdout pipeline, thought to keep it like that in case it moves back there. But I just removed this log line, since it's not very insightful anyways.

2025-03-18 13:24 UTC, traines-source commented on build/ris-fetch.js
> +        throw new Error('File from previous run exists, consider deleting the tmp dir: ' + fileName);
I thought we had agreed that by splitting the build process in two parts we can leave it a non-transparent cache. I have now removed the `recursive: true` flag from the mkdir for the tmp directory, this way it directly throws and one has to delete the entire tmp directory in order to proceed.

2025-03-18 13:26 UTC, derhuerst commented on build/ris-fetch.js
> +        throw new Error('File from previous run exists, consider deleting the tmp dir: ' + fileName);
Why not just just overwrite the file then?

2025-03-18 13:27 UTC, traines-source commented on build/ris-merge.js
> +const data = new PassThrough({
I had just taken that from the hafas pipeline, but yeah I guess at this point it doesn't make that much sense anymore

2025-03-18 13:31 UTC, traines-source commented on build/ris-merge.js
> +            // use groupMembers from grouped results
A group station should never have different `groupMembers` in different API responses, but it may appear in multiple different API responses (due to overlapping bounding boxes and the "zooming" logic), so you only want to add the group members once. And for simplicity, both grouped and simple files are read at the same time, so we need to add the group members in case the single result for this station was read first.

2025-03-18 13:36 UTC, traines-source commented on build/ris-merge.js
> +const verifyCompleteness = (stops) => {
It's an optional verification with an external file from somewhere else (originally the stations obtained from HAFAS, now possibly from the previous run from RIS), in order to detect any suddenly missing stations, like originally Groß Gerau. We could actually change it to `full.json` to read and compare with the previous run before the file is overwritten.

2025-03-18 14:27 UTC, traines-source commented on package.json
>  		"through2-concurrent": "^2.0.0",
It's used in simplify.js, isn't it?

2025-03-18 14:45 UTC, derhuerst commented on build/ris.js
> +            s.ril100Ids = stadaStop.ril100Identifiers.map(r => r.rilIdentifier); // TODO more precise mapping to evas?
@traines-source Here in `db-hafas-stations`, we could add a flag "is it operated by Deutsche Bahn?" (is that the criteria for inclusion in the StaDia API btw?), and then deprecate `db-stations` with a remark to use this flag for filtering.

2025-03-18 14:48 UTC, derhuerst commented on package.json
>  		"through2-concurrent": "^2.0.0",
Nope, that's `through2`.

2025-03-18 14:53 UTC, derhuerst commented on build/ris-merge.js
> +const verifyCompleteness = (stops) => {
Shall we put it in a separate script then?

2025-03-18 15:11 UTC, traines-source commented on build/ris-merge.js
> +const verifyCompleteness = (stops) => {
It's now part of the pipeline and compares with the previous full.json, if one exists, I thought this could be quite useful at least when operating it locally.

2025-03-18 16:19 UTC, derhuerst commented on build/ris-merge.js
> +            // use groupMembers from grouped results
I still don't understand it, but I trust you. 😄

2025-03-18 16:35 UTC, traines-source commented on package.json
>  		"through2-concurrent": "^2.0.0",
mmh in any case I had removed it and something ceased to work

2025-03-18 16:40 UTC, merged

2025-03-18 16:41 UTC, derhuerst commented
Thanks! 🚀

2025-05-07 13:57 UTC, networkException commented on build/ris.js
> +            s.ril100Ids = stadaStop.ril100Identifiers.map(r => r.rilIdentifier); // TODO more precise mapping to evas?
> `https://apis.deutschebahn.com/db/apis/ris-stations/v1/batch/versions` (note the different URL to e.g. `https://apis.deutschebahn.com/db-api-marketplace/apis/ris-stations/v1/stop-places/by-keys`) still gives Unauthorized for normal API keys...

Do you know how that endpoint works? Feel free to message me on Matrix (`@networkexception:nwex.de`) in case thats confidential somehow

2025-05-07 21:18 UTC, traines-source commented on build/ris.js
> +            s.ril100Ids = stadaStop.ril100Identifiers.map(r => r.rilIdentifier); // TODO more precise mapping to evas?
The `/batch/versions` one? You can only access this with a special API key, which at least I don't have. I can send you the OpenAPI docs for that. But if you have such an API key, you also have the documentation I guess :D